resolver: lts-13.6  # Adapt this as needed
packages:
  - .
extra-deps:
  - hakyll-4.12.5.1  # Or a later version you installed
  - lrucache-1.2.0.1@sha256:18fc3d7052012c7ab3cd395160f34b53c5e1ec5379cc45185baf35b90ffadc2e